import "@/app/globals.css";
import NavbarWrapper from "../containers/wrappers/navbarWrapper";
import Footer from "@/components/footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export async function generateMetadata() {
  return {
    title: {
      default: "غُرباء | منصة الشهداء",
      template: "%s",
    },
    description: "Generated by create next app",
    icons: {
      apple: "/zad-logo.svg",
      icon: "/zad-logo.svg",
    },
  };
}

// Viewport export remains separate
export const viewport = "width=device-width, initial-scale=1";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar">
      <body
        suppressHydrationWarning={true}
        dir="rtl"
        className="relative h-full w-full bg-background_light"
      >
        <ToastContainer
          position="top-center"
          autoClose={2000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={true} // Right-to-left for Arabic
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <NavbarWrapper /> {/* Use the server-side wrapper */}
        <div className="mt-[70px] min-h-screen">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
