import Footer from "@/components/footer";
import Comments from "@/containers/home/comments";
import Features from "@/containers/home/recentlyAddedMartyers";
import Hero from "@/containers/home/hero";
import Landing from "@/containers/home/landing";
import MartyersStatistics from "@/containers/home/martyersStatistics";
import TodaysMartyer from "@/containers/home/todaysMartyer";

export async function generateMetadata() {
  return {
    title: {
      default: "Ghorabaa | غُرباء",
      template: "%s",
    },
    description: "Generated by create next app",
    icons: {
      apple: "/zad-logo.svg",
      icon: "/zad-logo.svg",
    },
  };
}

// Viewport export remains separate
export const viewport = "width=device-width, initial-scale=1";

export default function Home() {
  return (
    <>
      <Landing />
      <MartyersStatistics />
      <div className="container mx-auto">
        <TodaysMartyer />
        <Features />
      </div>
      <div className="container">
        {/* <Hero /> */}
        <Comments />
      </div>
      {/* <Footer /> */}
    </>
  );
}
