import "@/app/globals.css";

export async function generateMetadata() {
  return {
    title: {
      default: "غُرباء | الفعاليات القادمة",
      template: "%s",
    },
    description: "Generated by create next app",
    icons: {
      apple: "/zad-logo.svg",
      icon: "/zad-logo.svg",
    },
  };
}

// Viewport export remains separate
export const viewport = "width=device-width, initial-scale=1";

export default function layout({ children }: { children: React.ReactNode }) {
  return <div>{children}</div>;
}
